version: "3.2"
services:
  #db: use Maria DB as our backend DB
  db:
    image: mariadb
    ports:
      - "<%=dbPort%>:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secret/password
    volumes:
      - type: bind
        source: ./mysql/conf.d/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./mysql/data
        target: /var/lib/mysql
      # - type: bind
      #   source: ./mysql/conf.d
      #   target: /etc/mysql/conf.d
      - type: bind
        source: ./mysql/key
        target: /key
      - type: bind
        source: ./mysql/password
        target: /secret/password
    # on windows: use this command. (be sure to clear out mysql/data folder)
    # command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
  #/db

  # include ArrangoDB for AB definitions
  arangodb:
    image: arangodb
    ports:
      - "<%=arangoPort%>:8529"
    environment:
      ARANGO_ROOT_PASSWORD: "<%=arangoPassword%>"
    volumes:
      - type: bind
        source: ./arango/data
        target: /var/lib/arangodb3
      - type: bind
        source: ./arango/apps
        target: /var/lib/arangodb3-apps
      - type: bind
        source: ./arango/init
        target: /docker-entrypoint-initdb.d

  #api_sails: the AppBuilder Developer Container
  api_sails:
    image: skipdaddy/install-ab:developer_v2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "1337:1337"
      - "9229:9229"
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./developer/app_builder
        target: /app/node_modules/app_builder
      - type: bind
        source: ./developer/appdev-core
        target: /app/node_modules/appdev-core
    command: ["node", "--inspect", "--max-old-space-size=2048", "--stack-size=2048", "app.js"]
  #/api_sails
