version: "3.2"
services:
  # use Maria DB as our backend DB
  db:
    image: mariadb
#    restart: always
    ports:
      - "8889:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./mysql/data
        target: /var/lib/mysql

  # include ArrangoDB for AB definitions
  arangodb:
    image: arangodb
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: "root"
    volumes:
      - type: bind
        source: ./arango/data
        target: /var/lib/arangodb3
      - type: bind
        source: ./arango/apps
        target: /var/lib/arangodb3-apps
      - type: bind
        source: ./arango/init
        target: /docker-entrypoint-initdb.d

  # download and install the AppBuilder Developer Container
  AppBuilder:
    image: skipdaddy/install-ab:developer_v2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "1337:1337"
      - "9229:9229"
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
    command: ["node", "--inspect", "--max-old-space-size=2048", "--stack-size=2048", "app.js"]
