version: "3.2"
volumes:
  mysql_data:

networks:
  default:
    attachable: true

services:
  #db: use Maria DB as our backend DB
  db:
    image: docker.io/digiserve/ab-db:$AB_DB_VERSION
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    # on windows: use this command. (be sure to clear out mysql/data folder)
    # command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    ######
    # when there is a problem with : Error: ER_CRASHED_ON_USAGE: Table 'AAAAAA' is marked as crashed and should be repaired
    # this can happen with the alter table algorithm: try the safest(and slowest) COPY
    # command: ["mysqld", "--alter-algorithm=copy"]
  #/db