
  #nginx setup
  web:
    image: nginx
    ports:
      - "<%=port%>:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/html
        target: /usr/share/nginx/html
      - nginx_etc:/etc
      - files:/data
      - type: bind
        source: ./assets
        target: /data/assets
    depends_on:
      - api_sails
  #/nginx