version: "3.9"

  #[name]: [description]
  [name]:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    hostname: [name]
    volumes:
      - type: bind
        source: ./developer/[name]
        target: /app
    depends_on:
      - redis
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/[name]
