

  #[name]: [description]
  [name]:
    image: node
    # ports:
    #   - "9229:9229"
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/[name]
        target: /app
      - config:/app/config
    depends_on:
      - redis
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/[name]
