

  #[serviceName]: [description]
  [serviceName]:
    image: node
    # ports:
    #   - "9229:9229"
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/[name]
        target: /app
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
    depends_on:
      - redis
    working_dir: /app
    command: npm run dev
  #/[serviceName]
